title: Frédéric Jurie
#logo: /assets/img/logo.png

logo: id.jpg

description: '
Frédéric Jurie\
ENSICAEN,\
6 Boulevard Maréchal Juin - CS 45053\
14050 CAEN cedex 4, FRANCE\
Room FB-222\
@: frederic.jurie@unicaen.fr\
Tel: +33(0)231 455 453'

show_downloads: false

google_analytics:

theme: jekyll-theme-minimal
