title: Frédéric Jurie
#logo: /assets/img/logo.png

logo: id.jpg

description: '
Frédéric Jurie <br>
ENSICAEN, <br>
6 Boulevard Maréchal Juin - CS 45053 <br>
14050 CAEN cedex 4, FRANCE <br>
email: frederic.jurie@gmail.com <br>
Skype: fjurie <br>
Tel: +33(0)231 455 453'

Skype: fjurie
note: note

show_downloads: false

google_analytics:

theme: jekyll-theme-minimal
