title: Frédéric Jurie
#logo: /assets/img/logo.png
logo: id.jpg
description: Frederic is a professor of computer science at the University of Caen.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
