title: Frédéric Jurie
#logo: /assets/img/logo.png

logo: id.jpg

description: ENSICAEN,<br/>
6 Boulevard Maréchal Juin - CS 45053<br/>
14050 CAEN cedex 4, FRANCE<br/>
Room FB-222<br/>
<br/>
@: frederic.urie@unicaen.fr<br/>
Tel: +33(0)231 455 453<br/>

show_downloads: false

google_analytics:

theme: jekyll-theme-minimal
