title: Frédéric Jurie
#logo: /assets/img/logo.png

logo: id.jpg

description: '
Frédéric Jurie <br>
ENSICAEN, <br>
6 Boulevard Maréchal Juin - CS 45053 <br>
14050 CAEN cedex 4, FRANCE <br>
email: frederic.jurie@gmail.com <br>
Skype: fjurie <br>
Tel: +33(0)231 455 453<br>
<iframe width="100%"frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/?ie=UTF8&amp;ll=49.212544,-0.368648&amp;spn=0.001342,0.003042&amp;t=m&amp;z=18&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/?ie=UTF8&amp;ll=49.212544,-0.368648&amp;spn=0.001342,0.003042&amp;t=m&amp;z=18&amp;source=embed" style="color:#0000FF;text-align:left">View Larger Map</a></small>'

Skype: fjurie
note: note

show_downloads: false

google_analytics:

theme: jekyll-theme-minimal
