title: Frédéric Jurie
#logo: /assets/img/logo.png
logo: id.jpg
description: Frederic is a professor of Computer Science at the University of Caen Normandie.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
